### ISSUE TITLE
Possible application: Stan on AWS lambda

### ISSUE THREAD

**Issue by noamross** [sjackman/lambdar#7]
I think a great application for lambda would be running Stan models - typically compute-intensive but not always high memory usage. I could see a package specifically for this, which would

- Grab a pre-built AWS lambda Docker image with R, Stan and related dependencies
- Run something like `stan_model_lambda()`, a wrapper around `stan_model`, which compiles the stan models in the AWS environment, packages it together and uploads to the user account.
    -   This would create a new object type `stanmodel_lambda`. It could inherit from `stanmodel` and still print the Stan code, etc., based on a local object, but calls running the model would run on AWS.
    -   It would have some reasonable but configurable defaults for memory usage.
    -   Dirk's [recent post](dirk.eddelbuettel.com/blog/2017/08/20/#010_stripping_shared_libraries) on symbol stripping is a good idea for reducing the package size.
- Methods for functions like `rstan::sampling` to run MCMC chains on AWS and retrieve results, including running multiple chains via multiple calls to AWS and combining via `sflist2stanfit()`.
    -   A local/debug flag could run the model in the local Docker container. 
    -   A flag or function might estimate or at least report the cost.

This would also work for *pomp* or similar compiled-model MCMC tasks.

I would like to work on this.  Not 100% sure when I'll find the time but it will be useful for us at work as our increased number of Stan users is slowly pushing the limits of our local compute resources.

**Comment by noamross** [comment]
I guess it's possible one may not even need R on AWS to do this, as Stan has a standalone binary with a CLI.

**Comment by sjackman** [comment]
Take a look at the AWS resource limits: http://docs.aws.amazon.com/lambda/latest/dg/limits.html
Is five minutes enough time for your purposes?

**Comment by sjackman** [comment]
If you don't need R, one option is to install the standalone Stan executables using Linuxbrew.

**Comment by noamross** [comment]
The five minute thing does kind of torpedo the idea.  Most of the <5 minute applications here are fine to do locally.  It's the long runs that would be nice to move to a cloud instance. I see google cloud functions has a similar limit (9 minutes). 

I guess in my case lambda is more appropriate for something massively parallel that could be broken into lots of <5 minute chunks, which isn't the case for MCMC chains.  Something more similar to JD Long's [segue package](https://code.google.com/archive/p/segue/) might make more sense.  Its `emrapply()` spins up an AWS Map-Reduce cluster, runs code in parallel, then shuts it down.  For something with long compute times, the spin-up time shouldn't be as important. Maybe a custom **future** plan that does this is the way to go.

Yeah, a **future.cloudservices** package might be where it's at.

**Comment by sjackman** [comment]
Sounds like AWS Batch would be a better fit for your use case. https://aws.amazon.com/batch/
@HenrikBengtsson Any thoughts on `future.aws.batch`?
